const state = { files: [] };
const $ = (selector, root = document) => root.querySelector(selector);
const dropzone = $('#dropzone'); const picker = $('#files'); const upload = $('#upload');
function selectFiles(files) { state.files = [...files].filter(file => ['image/jpeg','image/png','image/webp'].includes(file.type)); upload.disabled = !state.files.length; $('#status').textContent = state.files.length ? `${state.files.length}枚を選択中` : ''; }
dropzone.addEventListener('click', () => picker.click()); dropzone.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') picker.click(); }); picker.addEventListener('change', () => selectFiles(picker.files));
['dragenter','dragover'].forEach(type => dropzone.addEventListener(type, e => { e.preventDefault(); dropzone.classList.add('drag'); })); ['dragleave','drop'].forEach(type => dropzone.addEventListener(type, e => { e.preventDefault(); dropzone.classList.remove('drag'); })); dropzone.addEventListener('drop', e => selectFiles(e.dataTransfer.files));
upload.addEventListener('click', () => { const data = new FormData(); state.files.forEach(file => data.append('photos', file)); const xhr = new XMLHttpRequest(); const progress = $('.progress'); progress.hidden = false; upload.disabled = true; xhr.upload.onprogress = e => { if (e.lengthComputable) $('.progress div').style.width = `${e.loaded / e.total * 100}%`; }; xhr.onload = async () => { const result = JSON.parse(xhr.responseText || '{}'); if (xhr.status >= 400) $('#status').textContent = result.error || 'アップロードに失敗しました'; else { $('#status').textContent = `${result.created.length}枚を追加しました${result.errors.length ? `（${result.errors.join(' / ')}）` : ''}`; state.files=[]; picker.value=''; await load(); } progress.hidden=true; upload.disabled=!state.files.length; }; xhr.onerror = () => { $('#status').textContent='通信に失敗しました'; upload.disabled=false; }; xhr.open('POST','/api/photos'); xhr.send(data); });
async function load() { const response = await fetch('/api/photos'); const {photos} = await response.json(); $('#count').textContent = `${photos.length} PHOTOS`; const list=$('#photos'); list.replaceChildren(); photos.forEach(photo => { const node=$('#photo-template').content.cloneNode(true); const article=$('article',node); $('img',article).src=photo.thumbnail_url; $('img',article).alt=photo.alt_text || photo.title || ''; ['title','description','alt_text','sort_order'].forEach(key => $(`[name=${key}]`,article).value=photo[key] ?? ''); $('[name=is_published]',article).checked=photo.is_published; $('small',article).textContent=`${photo.original_filename} · ${photo.width}×${photo.height} · ${new Date(photo.created_at).toLocaleString('ja-JP')}`; $('[data-action=save]',article).onclick=async()=>{ const body={}; ['title','description','alt_text'].forEach(key=>body[key]=$(`[name=${key}]`,article).value); body.sort_order=Number($('[name=sort_order]',article).value); body.is_published=$('[name=is_published]',article).checked; const res=await fetch(`/api/photos/${photo.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); $('[data-action=save]',article).textContent=res.ok?'保存済み':'エラー'; setTimeout(()=>$('[data-action=save]',article).textContent='保存',1200); }; $('[data-action=delete]',article).onclick=async()=>{ if(confirm(`「${photo.title || photo.original_filename}」を削除しますか？`)){ await fetch(`/api/photos/${photo.id}`,{method:'DELETE'}); load(); } }; list.append(node); }); }
$('#reload').addEventListener('click',load); load();
